### ISSUE TITLE
I couldn't find demo/runDemo.sh /pathogenicVariants.vcf

### ISSUE THREAD

**Issue by rescuz** [ding-lab/CharGer#29]
Hello,I want to  ask whether the demo/runDemo.sh /pathogenicVariants.vcf  file is lost? I can't find pathogenicVariants.vcf  mentioned in runDemo.sh file.
Thnaks for your help.

**Comment by fernanda-rodrigues** [comment]
Hi @rescuz 
I believe that was a typo in the runDemo.sh file. I apologize for that.
If you look at the actual charger command that the script is running, you will see it does not take the pathogenicVariants.vcf file into account.

If you do want to use a similar file in your analysis, there is an example vcf for pathogenic variants in the PanCanAtlasData directory (PanCanAtlasData/emptyRemoved_20160428_pathogenic_variants_HGVSg_VEP.vcf.gz).
This file was used as a CharGer input in our Pan-Cancer germline study (https://doi.org/10.1016/j.cell.2018.03.039). Just make sure to decompress it before use.

Hope this helps
Fernanda
