### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by ChengYunazhi** [ding-lab/CharGer#3]
Hi 

I installed CharGer succesfully, but failed to run it, here it was:

![q1](https://user-images.githubusercontent.com/13846735/40360979-65f7a7c2-5dfa-11e8-9e15-6b664038a440.png)

error:

![q2](https://user-images.githubusercontent.com/13846735/40361023-872fc488-5dfa-11e8-812e-3b4c3897835b.png)

**Comment by rmashl** [comment]
It appears your installation in incomplete. We have recently updated installation instructions. Could you try again using one of those approaches?
