### ISSUE TITLE
can't input maf.file

### ISSUE THREAD

**Issue by rescuz** [ding-lab/CharGer#30]
Hello,
When I input maf.file ，charger always print "CharGer Error: bad .maf file ",so i want to know whether there are some errors in my maf.file .I paste my  maf.file content in follow,many thanks!

maf.file:
 1 Hugo_Symbol     Entrez_Gene_Id  Chromosome      Start_position  End_position    Variant_Classification  Variant_Type    Reference_Allele        Tumor
      2 CDK11A  728642  1       1647893 1647894 In_Frame_Ins    INS     -       -       TTTCTT  rs200224067|rs199866927|rs144636354                   3 PRDM2   7799    1       14106394        14106395        In_Frame_Ins    INS     -       -       CTC     rs2308040|rs148293494|rs59028030        
      4 SLC25A34        284723  1       16063253        16063265        Frame_Shift_Del DEL     CAGCCTGGCGTGC   CAGCCTGGCGTGC   -                       BGI-0
      5 SERINC2 347735  1       31905889        31905890        In_Frame_Ins    INS     -       -       CAG     rs33956499|rs3050461|rs5773362  byFrequency
      6 GJB4    127534  1       35227008        35227011        Frame_Shift_Del DEL     TGTC    TGTC    -       rs146812843             BGI-0103-ESCC-060N
      7 MAP7D1  55700   1       36643701        36643703        In_Frame_Del    DEL     AGA     AGA     -       rs3045695|rs141305015|rs200892098       byFre
      8 KLF17   128209  1       44596380        44596382        In_Frame_Del    DEL     CAA     CAA     -       rs200059598|rs34057178  byFrequency         9 CYP4B1  1580    1       47280747        47280748        Splice_Site     DEL     AT      AT      -       rs55835239|rs397687617|rs3215983

**Comment by fernanda-rodrigues** [comment]
Can you send me the command you used to run CharGer? Also, can you attach your maf file here so I can do some testing? You seem to have line numbers in the version you pasted here, which could be part of the issue ...

**Comment by fernanda-rodrigues** [comment]
I am closing this issue. Please do not hesitate to contact us if you have further questions. 

Fernanda
