### ISSUE TITLE
biomine warning

### ISSUE THREAD

**Issue by rescuz** [ding-lab/CharGer#36]
Hello,
I want to ask the reason about the biomine warning :
biomine warning: EX not found in conversion tables
biomine warning: ECPIC not found in conversion tables
biomine warning: EX not found in conversion tables
biomine warning: ECPIC not found in conversion tables
biomine warning: EX not found in conversion tables
biomine warning: ECPIC not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables
biomine warning: RVEEVQNVIN not found in conversion tables

And this is my shell content:charger -f ${in} -o ${out} -D --inheritanceGeneList ${pvs1}   -E -l --mac-clinvar-tsv ${clinvar}  --PP2GeneList ${pp2}  --BP1GeneList ${bp1} -H ${pm5} -g ${mmGenes} -z ${mmVariants} --exac-vcf ${ExAC};
Looking forward to your reply ,thanks

**Comment by fernanda-rodrigues** [comment]
Hello @rescuz 
I apologize for the delay in my response.
These warnings can be ignored; they do not affect your results :)

Let me know if you need further help!

**Comment by yubau1112** [comment]
Will it be modified in the future to remove the warning? Or is there a way to turn it off?

**Comment by ccwang002** [comment]
@yubau1112 we are working on an update, but it will take another few months. So the warnings will stay around for a while.
