### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by yubau1112** [ding-lab/CharGer#38]
I already installed Charger and run "runDemo.sh", but I get a lot of "Warning" message

[charged.demo.log](https://github.com/ding-lab/CharGer/files/4151712/charged.demo.log)

**Comment by yubau1112** [comment]
I already installed Charger and run "runDemo.sh", but I get a lot of "Warning" message

[charged.demo.log](https://github.com/ding-lab/CharGer/files/4151708/charged.demo.log)

**Comment by fernanda-rodrigues** [comment]
Hi @yubau1112 

The warning messages you see can be ignored. The should not affect your results.
We are currently working on further improvements to this tool and turning off some of these warning statements.
Please let us know if you have further concerns.

Fernanda Martins Rodrigues
CharGer Team

**Comment by yubau1112** [comment]
![image](https://user-images.githubusercontent.com/45645173/74492192-0d05b800-4f09-11ea-951d-5401e186e5a1.png)

I get so much  "Unsupported" message, is right?

**Comment by yubau1112** [comment]
[clinvar_20200210.vep_1000.vcf.txt](https://github.com/ding-lab/CharGer/files/4203558/clinvar_20200210.vep_1000.vcf.txt)


charger -f ~/VEP/ensembl-vep/clinvar_20200210.vep.vcf -o clinvar_20200210.vep.charger.l.vcf -l

![image](https://user-images.githubusercontent.com/45645173/74515349-5b3aab80-4f49-11ea-9a7e-b713c4ee71e4.png)

**Comment by fernanda-rodrigues** [comment]
Hi @yubau1112 

**Regarding the the "Unsupported" message you see:** when you supply CharGer with a VEP annotated file, it looks for the following population allele frequencies in this order: gnomAD, ExAC, and 1000Genomes.
It prioritizes gnomAD over ExAC and so on. When CharGer does not find that allele frequency (either because the file is not annotated with that allele frequency or because the variant is not present in that particular database, it looks for the next one in that list). That was a message meant for developing purposes that I forgot to turn off. I will submit an update with that message removed. In summary, you can ignore that message. Your VEP annotation seems perfectly fine, according to the example file you submitted. 

**Regarding the error you mention in your second post:** I was not able to reproduce it. I ran your VEP annotated VCF file through CharGer and I do not receive any errors.
May I ask how you installed CharGer? Did you use the conda environment, as recommended?
This seems like a python version related issue. CharGer currently requires python 2.7 to run. If your default python version is 3x, it will issue errors like this.

**Comment by yubau1112** [comment]
thanks to your reply
Yes, I use the conda environment. 
but I think you are right. 
I really use python3
maybe this is python version related issue
I will try python 2.7

**Comment by fernanda-rodrigues** [comment]
@yubay1112
The conda environment installation is to create an environment with python2, suitable for CharGer.
Make sure that you activate your conda environment prior to running CharGer or that you add the path to charger to your .bashrc file, as instructed.
Please let us know if you have any further questions.

**Comment by yubau1112** [comment]
I reinstall CharGer step by step:

mkdir CharGer
cd CharGer
wget https://repo.anaconda.com/archive/Anaconda2-5.2.0-Linux-x86_64.sh
bash Anaconda2-5.2.0-Linux-x86_64.sh

Do you accept the license terms? [yes|no]
[no] >>> yes

Anaconda2 will now be installed into this location:
/home/yubau/anaconda2

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/yubau/anaconda2] >>>

Do you wish the installer to prepend the Anaconda2 install location
to PATH in your /home/yubau/.bashrc ? [yes|no]
[no] >>>yes

Do you wish to proceed with the installation of Microsoft VSCode? [yes|no]
>>> no

(finish install anaconda)

conda create --name CharGer python=2.7
conda activate CharGer

which conda
~/anaconda2/bin/conda

~/anaconda2/bin/conda --version
conda 4.5.4

which pip
/usr/local/bin/pip

/usr/local/bin/pip --version
pip 19.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

conda install pysam

wget -O CharGer.zip https://github.com/ding-lab/CharGer/archive/master.zip
unzip CharGer.zip
mv CharGer-master/ CharGer
cd CharGer
pip install .
conda deactivate
vim ~/.bashrc 

I found:
# added by Anaconda2 installer
export PATH="/home/yubau/anaconda2/bin:$PATH"

and add
export PATH="/home/yubau/anaconda2/envs/CharGer/bin:$PATH"

Re-login Linux terminal 

cd /home/yubau/CharGer_test2/CharGer/Demo

conda activate CharGer

***
previously, I download clinvar_20200210.vcf from clinivar
we want to used clinvar_20200210.vcf as test

we download clinvar_20200210.vcf from ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/

so my VEP command is:
`./vep -i clinvar_20200210.vcf --cache tmp --fasta ~/.vep/homo_sapiens/99_GRCh37 -o clinvar_20200210.vep.vcf --force_overwrite --everything --fork 48 --assembly GRCh37 --port 3337 --vcf --format vcf --symbol --terms SO --tsl --dir_plugins /home/yubau/.vep/Plugins/ --af_exac`

VEP run finish, result is good, no report any warning or error
I upload result on google drive
https://drive.google.com/open?id=1YnP6bKxjN1MUBiEUKTPqV-rnQlqXacPe
***

than, I run charger
my charger command is:
`charger -f clinvar_20200210.vep.vcf -o clinvar_20200210.vep.charger.l.vcf -l --exac-vcf ExAC.r1.sites.vep.vcf --mac-clinvar-tsv clinvar_alleles.multi.b37.tsv --perl /home/yubau/perl --vep-script /home/yubau/VEP/ensembl-vep --vep-config /home/yubau/VEP/ensembl-vep/t/Config.t --vep-cache /home/yubau/.vep --vep-version 99 --vep-output clinvar_20200210_output.charger.vep.vcf --grch 37 --ensembl-release 75 --reference-fasta /home/yubau/.vep/homo_sapiens/99_GRCh37 --fork 48`

![image](https://user-images.githubusercontent.com/45645173/74799289-11681180-530b-11ea-9f16-74bbaffe0e42.png)

but, if I execute:
charger -f clinvar_20200210.vep.vcf -o clinvar_20200210.vep.charger.x.vcf -x
I can get result!

![image](https://user-images.githubusercontent.com/45645173/74799388-58560700-530b-11ea-9ac8-f454c16b2418.png)

but in CharGer_Classification column have so many Uncertain Significance and not have Pathogenic
really something wrong!

----------------------------------------------
Summary:
My boss says charger is a very very very important tool !
In the future, all clinical vcf files will need to use charger to annotate all variants.
Ask me to put the test charger first on the work list!
but I always get error..

thanks

yubau, from taiwan
