### ISSUE TITLE
run demo.sh, report error

### ISSUE THREAD

**Issue by xuanzhu1213** [ding-lab/CharGer#39]
I already installed Charger, 
![image](https://user-images.githubusercontent.com/26055504/74727091-94418b80-527b-11ea-9a04-df79714f8304.png)

![image](https://user-images.githubusercontent.com/26055504/74726955-547aa400-527b-11ea-83ba-668d57b23be0.png)

**Comment by fernanda-rodrigues** [comment]
Hello @xuanzhu1213 
Thank you for using our tool.
I cannot reproduce your error. It seems like your installation had some issues.
May I ask how you installed charger? We recommend that you install with conda, as indicated in the README. 
It seems like the problem could be there.
If you could show me your installation steps, I could help you troubleshoot.

**Comment by xuanzhu1213** [comment]
I  installed the tool with conda, then it works.
