### ISSUE TITLE
can you give me an example command with run VEP?

### ISSUE THREAD

**Issue by yubau1112** [ding-lab/CharGer#40]
I want to use Local VEP when use charger

my command is:

(CharGer) [yubau@cmuh-i2 Demo]$ charger -f clinvar_20200210.vep.vcf -o clinvar_20200210.vep.charger.ltEx.tsv -l -t -E -x --exac-vcf ExAC.r1.sites.vep.vcf --mac-clinvar-tsv clinvar_alleles.multi.b37.tsv.gz --perl /home/yubau/perl --vep-script /home/yubau/VEP/ensembl-vep/vep --vep-config /home/yubau/VEP/ensembl-vep/t/Config.t --vep-cache /home/yubau/.vep --vep-version 99 --vep-output clinvar_20200210_output.charger.vep.vcf --grch 37 --ensembl-release 75 --reference-fasta /home/yubau/.vep/homo_sapiens/99_GRCh37 --fork 48

any wrong?

Can you give me an example command when use charger with run VEP?

thanks

**Comment by ccwang002** [comment]
We will drop the support to call VEP directly from CharGer in future. It's better if you do it in two steps: 1) run VEP to annotate the VCF, and 2) run CharGer with the VEP annnotated VCF. If the two-step approach doesn't work, let us know.

**Comment by yubau1112** [comment]
So, you mean:
you not Suggest use ”Local VEP ” function in charger ?
 
Another questions is:
I really want to close so many warring message when run charger, have any way to close?

**Comment by yubau1112** [comment]
I fund a bug:

/home/yubau/anaconda2/envs/CharGer/lib/python2.7/site-packages/biomine/webapi/entrez/entrezapi.py 

Line  332 and Line  333 entrezaip ---need to modify-> entrezapi 

right?

**Comment by ccwang002** [comment]
I am sorry that you have to bear with the warnings for a while, until we finish an update on CharGer. The warning doesn't affect the results.
