### ISSUE TITLE
I can not get any output file using v0.6.0b1 version

### ISSUE THREAD

**Issue by yubau1112** [ding-lab/CharGer#41]
vep command:
~/VEP/ensembl-vep/vep -i HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep.vcf --assembly GRCh38 --cache --dir_plugins /home/yubau/.vep/Plugins --everything --fasta /home/yubau/.vep/homo_sapiens/99_GRCh38 --force_overwrite --fork 48 --format vcf --input_file HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vcf --offline --output_file HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep.vcf --symbol --terms SO --tsl --vcf

vcf using VEP annotated file (head -n 1000) (Total 4,773,130 line when run charger):
[HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep_1000.txt](https://github.com/ding-lab/CharGer/files/4273663/HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep_1000.txt)

install:
mkdir CharGer_test_python38
cd CharGer_test_python38
conda create --name CharGer_python_38  python=3.8
conda activate CharGer_python_38
pip install pysam

(CharGer_python_38) [yubau@cmuh-i2 CharGer]$ conda list
\# packages in environment at /home/yubau/anaconda2/envs/CharGer_python_38:
\#
\# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
attrs                     19.3.0                   pypi_0    pypi
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py38_0
charger                   0.6.0b1                  pypi_0    pypi
cyvcf2                    0.11.6                   pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
loguru                    0.4.1                    pypi_0    pypi
ncurses                   6.2                  he6710b0_0
numpy                     1.18.1                   pypi_0    pypi
openssl                   1.1.1d               h7b6447c_4
pip                       20.0.2                   py38_1
pysam                     0.15.4                   pypi_0    pypi
python                    3.8.1                h0371630_1
readline                  7.0                  h7b6447c_5
setuptools                45.2.0                   py38_0
sqlite                    3.31.1               h7b6447c_0
tk                        8.6.8                hbc83047_0
wheel                     0.34.2                   py38_0
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3

(CharGer_python_38) [yubau@cmuh-i2 CharGer]$ pip install --pre -i https://pypi.org/simple/ --extra-index-url https://test.pypi.org/simple/ charger

command:

(CharGer_python_38) [yubau@cmuh-i2 CharGer]$ charger --input HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep.vcf --output HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep.charger.tsv    INFO     | Running CharGer v0.6.0b1 with parameters: --input HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep.vcf --output HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep.charger.tsv

----screen info start-------------------------------------------------------------------------------------
INFO     | Validate the given config
DEBUG    | Given config: CharGerConfig(input=PosixPath('HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep.vcf'), output=PosixPath('HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep.charger.tsv'), hotspot3d_cluster=None, pathogenic_variant=None, override_variant_info=False, include_vcf_details=False, clinvar_table=None, rare_threshold=0.0005, common_threshold=0.005, acmg_module_scores={'PVS1': 8, 'PS1': 7, 'PS2': 4, 'PS3': 4, 'PS4': 4, 'PM1': 2, 'PM2': 2, 'PM3': 2, 'PM4': 2, 'PM5': 2, 'PM6': 2, 'PP1': 1, 'PP2': 1, 'PP3': 1, 'PP4': 1, 'PP5': 1, 'BP1': -1, 'BP2': -1, 'BP3': -1, 'BP4': -1, 'BP5': -1, 'BP6': -1, 'BP7': -1, 'BS1': -4, 'BS2': -4, 'BS3': -4, 'BS4': -4, 'BA1': -8}, charger_module_scores={'PSC1': 4, 'PMC1': 2, 'PPC1': 1, 'PPC2': 1, 'BMC1': -2, 'BSC1': -6}, min_pathogenic_score=9, min_likely_pathogenic_score=5, max_likely_benign_score=-4, max_benign_score=-8, disease_specific=False, inheritance_gene_table=None, PP2_gene_list=None, BP1_gene_list=None)
INFO     | Read input VCF from HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep.vcf
DEBUG    | VEP version 99 with CSQ format [66 fields]: Allele,Consequence,IMPACT,SYMBOL,Gene,Feature_type,Feature,BIOTYPE,EXON,INTRON,HGVSc,HGVSp,cDNA_position,CDS_position,Protein_position,Amino_acids,Codons,Existing_variation,DISTANCE,STRAND,FLAGS,VARIANT_CLASS,SYMBOL_SOURCE,HGNC_ID,CANONICAL,MANE,TSL,APPRIS,CCDS,ENSP,SWISSPROT,TREMBL,UNIPARC,GENE_PHENO,SIFT,PolyPhen,DOMAINS,miRNA,HGVS_OFFSET,AF,AFR_AF,AMR_AF,EAS_AF,EUR_AF,SAS_AF,AA_AF,EA_AF,gnomAD_AF,gnomAD_AFR_AF,gnomAD_AMR_AF,gnomAD_ASJ_AF,gnomAD_EAS_AF,gnomAD_FIN_AF,gnomAD_NFE_AF,gnomAD_OTH_AF,gnomAD_SAS_AF,MAX_AF,MAX_AF_POPS,CLIN_SIG,SOMATIC,PHENO,PUBMED,MOTIF_NAME,MOTIF_POS,HIGH_INF_POS,MOTIF_SCORE_CHANGE
SUCCESS  | Read total 4,772,905 variants from the input VCF
WARNING  | Inheritance gene table is not provided, CharGer cannot make ACMG PVS1/PM4 calls or CharGer PSC1/PPC1 calls. Disable all these modules
WARNING  | CharGer cannot make PP2 calls without the given gene list. Disable PP2 module
WARNING  | CharGer cannot make BP1 calls without the given gene list. Disable BP1 module
INFO     | Skip matching ClinVar
INFO     | Run all ACMG modules
INFO     | Skipped PVS1 module
INFO     | Skipped PM4 module
INFO     | Run all CharGer modules
INFO     | Skipped PSC1 module
INFO     | Running PMC1 module
INFO     | Skipped PPC1 module
INFO     | Running PPC2 module
----screen info end-------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/45645173/75650243-4d4a9180-5c90-11ea-9681-c9a32fd2ae8e.png)

(CharGer_python_38) [yubau@cmuh-i2 CharGer]$ ls
CHANGES.rst               demo.vcf      demo.vep.vcf_summary.html  HCC297_S7_hg38.GATK.HaplotypeCaller.variants.vep.vcf  poetry.lock     README.md  setup.cfg  tests          tox.ini
clinvar_20200210.vep.vcf  demo.vep.vcf  docs                       LICENSE.txt                                           pyproject.toml  scripts    src        tox_conda.ini

(CharGer_python_38) [yubau@cmuh-i2 CharGer]$ python -V
Python 3.8.1
(CharGer_python_38) [yubau@cmuh-i2 CharGer]$ which python
~/anaconda2/envs/CharGer_python_38/bin/python
(CharGer_python_38) [yubau@cmuh-i2 CharGer]$ which pip
~/anaconda2/envs/CharGer_python_38/bin/pip
(CharGer_python_38) [yubau@cmuh-i2 CharGer]$ pip --version
pip 20.0.2 from /home/yubau/anaconda2/envs/CharGer_python_38/lib/python3.8/site-packages/pip (python 3.8)
(CharGer_python_38) [yubau@cmuh-i2 CharGer]$ charger --version
CharGer v0.6.0b1
(CharGer_python_38) [yubau@cmuh-i2 CharGer]$ which charger
~/anaconda2/envs/CharGer_python_38/bin/charger

I can not get any output file using v0.6.0b1 version

I used VEP to  annotate 0.5.4 version demo.vcf file and run charger  v0.6.0b1, than can not get any output file

Can you upload a demo.vcf for charger  v0.6.0b1 thanks!

yubau, from taiwan

**Comment by ccwang002** [comment]
You are using a pre-release version of CharGer and we haven't fully implemented all the functions from v0.5, as indicated by the README. Version 0.6.0 will likely take a few months to complete and will not be released soon.

Meanwhile, please continue to use the latest stable CharGer v0.5.4. Thank you.
