### ISSUE TITLE
installed Charger 0.5.4 but version in help is 0.5.3

### ISSUE THREAD

**Issue by nah2025** [ding-lab/CharGer#46]
When I run charger 0.5.4 to see the options, this is the output (first few lines):

CharGer - v0.5.3

Usage: charger <input file> [options]

Accepted input data files:
  -m Standard .maf
  -f Standard .vcf
  -T Custom .tsv

I checked if I downloaded the correct version.

**Comment by fernanda-rodrigues** [comment]
This is just a typo in the help file. It will be fixed. Thanks.
