### ISSUE TITLE
error: Hint: is the input amino acid change column correct , charger version 0.5.4

### ISSUE THREAD

**Issue by nah2025** [ding-lab/CharGer#47]
I'm running charger 0.5.4 on a gzipped VEP version 99 annotated file.  I'm getting a biomine error (could not find amino acid change or intronic change) as shown in the image below.

![image](https://user-images.githubusercontent.com/66339327/83580154-f466ef80-a543-11ea-9064-a57dbef57f7f.png)

Charger completes however and I'm able to see the scores for the variants.  I'm not sure if there are any variants missed though.  I've seen similar errors posted by other users (https://github.com/ding-lab/CharGer/issues/5) and the reply was that this error doesn't affect results and that it was fixed by version 0.5.4.  However, I still see the error.

**Comment by fernanda-rodrigues** [comment]
Hi @nah2025

As you can see in previous posts, this is a warning, not an error, issued by one of the dependent packages we use within CharGer. You can ignore it. It should not affect the results. 

Thanks
