### ISSUE TITLE
Reference for inheritanceGeneList 20160301_Rahman_KJ_KH_gene_table_CharGer.txt.gz

### ISSUE THREAD

**Issue by nah2025** [ding-lab/CharGer#48]
Hello,

I was looking for the reference for the inheritance gene list.. (20160301_Rahman_KJ_KH_gene_table_CharGer.txt.gz).

I found this paper from 2016 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4975511/bin/NIHMS69105-supplement-Supplementary_Table_1.xlsx) but it contains fewer genes than the one here: https://github.com/ding-lab/CharGer/tree/7d7d2911b89261fa5dceea6395a5d188a82757f2/PanCanAtlasData

Can the exact reference be shared?

**Comment by fernanda-rodrigues** [comment]
Hi
I apologize for the delay on getting back to you.
The list you're referring to contains 152 cancer predisposition genes, i.e. genes that have been reported to carry rare germline predisposition variants associated with cancer.
Please refer to our PanCancer germline paper for details on how this list was compiled: https://doi.org/10.1016/j.cell.2018.03.039

Thanks

**Comment by nah2025** [comment]
Thanks for the link.
