### ISSUE TITLE
problem running executable "charger" file

### ISSUE THREAD

**Issue by nitinroper** [ding-lab/CharGer#6]
After installing the program, I type
`charger` as suggested to view executable options and I receive the following error:
  

> File "/home/[username]/mycharger/bin/charger", line 256
>     print "CharGer ERROR: Command not recognized"
>                                                 ^
> SyntaxError: Missing parentheses in call to 'print

Any advice on how to fix this? Thank you

**Comment by amilacsw** [comment]
Thanks @nitinroper for reaching to us. This error should be coming from syntax difference between Python 2 and 3. Charger is built for Python 2. It seems like you are using Python 3. Please follow the installation steps given in the README to install Charger in a Python 2 environment.

**Comment by nitinroper** [comment]
I followed the installation steps exactly as listed in README. Any other potential reason for this issue?

**Comment by amilacsw** [comment]
Could you check your python version (enter `python -V` in terminal) and let us know what you see? Thanks!

**Comment by nitinroper** [comment]
`python -V`

Python 3.4.5 :: Continuum Analytics, Inc.

However, I also  have python 2 installed and I uninstalled python3.4.5 but have the same issue

**Comment by fernanda-rodrigues** [comment]
@nitinroper 
Sorry for the delay in addressing your issue.
I have updated the README file, including instructions on how to install CharGer within a conda environment.
That might solve your issue.
Please try it and let me know if you're still having problems.

Thanks!

**Comment by ghost** [comment]
I am currently in /home/<user>/anaconda2/CharGer directory
(base) $conda activate CharGer
(CharGer) $python -V
Python 2.7.18 :: Anaconda, Inc.
#now I want to test the vcf file
(CharGer) $ charger -f tests/examples/grch38_brca2_ashkenazi_jewish_founder.vcf -o testfile.vcf
command 'charger' not found, did you mean blabla

I did follow each of the steps in README.md. Please enlighten me.
